# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# ===================================================================
# Eureka server configuration (eureka.server.*)
#
# Full list of properties with default values at:
# https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaServerConfigBean.java
#
# Documentation at:
# https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/EurekaServerConfig.java
# ===================================================================

server:
    port: 8761

eureka:
    dashboard:
      path: /spring-cloud-register

management:
    context-path: /management

spring:
    application:
        name: spring-cloud-register
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

endpoints:
    shutdown:
        sensitive: false # 禁用密码验证
        enabled: true # 启用shutdown

info:
    build:
        artifact: "@project.artifactId@"
        name: "@project.name@"
        description: "@project.description@"
        version: "@project.version@"




