# ===================================================================
# Spring Boot configuration for the "test" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    env: test
    instance:
        hostname: 192.168.1.131
        appname: gaia
        prefer-ip-address: true
    server:
        # see discussion about enable-self-preservation:
        # https://github.com/jhipster/generator-jhipster/issues/3654
        enable-self-preservation: false
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://admin:${security.user.password:admin}@192.168.1.131:8761/eureka/

project:
    security:
        authentication:
            jwt:
                secret: d6877ac45344bb624472a12dd83bb6b3b7e63113
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds

spring:
    profiles:
        active: test
        include: native
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    cloud:
        config:
            server:
                native:
                    search-locations: file:./central-config
                prefix: /config
    thymeleaf:
        cache: false

security:
    user:
        name: admin
        password: 3UbNiNLZRKndx8
        role: USER,ADMIN
