# ===================================================================
# Spring Boot configuration for the "test" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    env: prod
    instance:
        hostname: localhost
        appname: spring-cloud-register
        prefer-ip-address: true
    server:
        # see discussion about enable-self-preservation:
        # https://github.com/jhipster/generator-jhipster/issues/3654
        enable-self-preservation: false
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://admin:fmsoiJ2ZCm2CvZ@localhost:8761/eureka/

project:
    security:
        authentication:
            jwt:
                secret: rk6vseyutytf77kg4iqkb78zxzukj4lrh292jhzn
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds

spring:
    profiles:
        active: prod
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    cloud:
        config:
            server:
                git:
                    uri: git@git.baokeyunguanjia.com:config/center.git
                prefix: /config
    thymeleaf:
        cache: false

security:
    user:
        name: admin
        password: fmsoiJ2ZCm2CvZ
        role: USER,ADMIN
