# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    env: lan
    instance:
        appname: spring-cloud-register
        prefer-ip-address: true
    server:
        # see discussion about enable-self-preservation:
        # https://github.com/jhipster/generator-jhipster/issues/3654
        enable-self-preservation: false
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://admin:${security.user.password:admin}@10.10.10.19:8761/eureka/

project:
    security:
        authentication:
            jwt:
                secret: d6877ac45344bb624472a12dd83bb6b3b7e63113
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds

spring:
    profiles:
        active: lan
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    boot:
        admin:
            url: http://10.10.10.19:9083
    cloud:
        config:
            server:
                native:
                    search-locations: file:./central-config
                git:
                    # sample prod config using the central-directory folder in the jhipster-registry github repos
                    uri: https://github.com/jhipster/jhipster-registry/
                    search-paths: central-config
                prefix: /config

    thymeleaf:
        cache: true

security:
    user:
        name: admin
        password: admin
        role: USER,ADMIN

server:
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
